name: Build & Publish Raygun4JS to the pre-release environment

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Grunt
      run: npm install -g grunt

    - name: Install node modules
      run: npm install

    - name: Build
      run: grunt build

    - name: Complete
      run: echo Build successfully completed!

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }} 
        aws-region: ${{ secrets.AWS_REGION }}
      
    - name: Publish to S3 Pre-release
      run: aws s3 sync ./dist ${{ secrets.AWS_PUBLISH_TARGET }}

    - name: Deployment Complete
      run: echo A new version of Raygun4JS has been deployed to pre-release!

    - name: Notify Slack
      id: slack
      uses: slackapi/slack-github-action@v1.14.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
